/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Beans.ClienteBeans;
import Beans.ProdutoBeans;
import Beans.VendaBeans;
import DAO.ClienteDAO;
import DAO.ProdutoDAO;
import DAO.VendaDAO;
import Utilitarios.modeloTabela;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author lucas
 */
public class Venda extends javax.swing.JFrame {
    float valorTotal = 0;
    
    

    /**
     * Creates new form Venda
     */
    public Venda() {
        initComponents();
    }
    public Venda(String codFunc) {
        initComponents();
        this.txtCodFuncionario.setText(codFunc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnBusca = new javax.swing.JButton();
        txtQunatidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtValorItem = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPesquisa = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaItemVenda = new javax.swing.JTable();
        btnFinalizar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        txtCodProduto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAbirVenda = new javax.swing.JButton();
        txtCodFuncionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCodVenda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario de Venda");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel2.setText("VENDAS");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Produto:");

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });

        btnBusca.setText("Busca");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        txtQunatidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQunatidadeFocusGained(evt);
            }
        });
        txtQunatidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQunatidadeKeyReleased(evt);
            }
        });

        jLabel3.setText("Qtd:");

        jLabel4.setText("Valor por item:");

        txtValorItem.setEnabled(false);

        txtValorTotal.setEnabled(false);

        jLabel5.setText("Valor total:");

        tabelaPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPesquisa);

        jLabel7.setText("Itens da venda:");

        tabelaItemVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabelaItemVenda);

        btnFinalizar.setText("FINALIZAR VENDA");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnAdicionar.setText("ADD");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jLabel8.setText("Cod Produto:");

        btnAbirVenda.setText("Abrir Venda");
        btnAbirVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbirVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(btnAbirVenda)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8)
                                                        .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnBusca))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(312, 312, 312)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(txtQunatidade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(41, 41, 41)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAdicionar)))))
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFinalizar)
                        .addGap(112, 112, 112)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQunatidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdicionar)
                            .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAbirVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBusca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        txtCodFuncionario.setEnabled(false);

        jLabel6.setText("Cod Func");

        txtCodVenda.setEnabled(false);

        jLabel9.setText("Cod Venda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtCodFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(76, 76, 76))
        );

        setSize(new java.awt.Dimension(846, 714));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        // TODO add your handling code here:
        ListarProdutos();
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void tabelaPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPesquisaMouseClicked
        // TODO add your handling code here:
        
        String nomeProduto = (String)tabelaPesquisa.getValueAt(tabelaPesquisa.getSelectedRow() ,1); 
        
        ProdutoDAO dao = new ProdutoDAO();
        dao.prod.setDescricao(nomeProduto);
        
        ProdutoBeans produto = dao.buscaProduto(dao.prod);
        

                if(produto.getCodProduto()!= 0){
                    //txtPesquisa.setText(String.valueOf(produto.getDescricao()));
                    txtQunatidade.setText("1");
                    txtCodProduto.setText(String.valueOf(produto.getCodProduto()));
                    txtValorItem.setText(String.valueOf(produto.getPreco()));
                    //txtValorTotal.setText(String.valueOf(produto.getPreco()));
                }
    }//GEN-LAST:event_tabelaPesquisaMouseClicked

    private void txtQunatidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQunatidadeFocusGained
        // TODO add your handling code here:
//       
    }//GEN-LAST:event_txtQunatidadeFocusGained

    private void txtQunatidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQunatidadeKeyReleased
        // TODO add your handling code here:
//        float valorTotal;
//        valorTotal = Float.parseFloat(txtValorItem.getText())*Integer.parseInt(txtQunatidade.getText());
//        
//        if(!txtQunatidade.getText().isEmpty())	{
//            valorTotal = Float.parseFloat(txtValorItem.getText())*Integer.parseInt(txtQunatidade.getText());
//             txtValorTotal.setText(String.valueOf(total));
//            
//        }
        
        
    }//GEN-LAST:event_txtQunatidadeKeyReleased

    private void btnAbirVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbirVendaActionPerformed
        // TODO add your handling code here:
        VendaBeans venda = new VendaBeans();
        venda.setValorTotal(Float.parseFloat("0"));


        if ((txtCodFuncionario.getText().isEmpty())) {
   JOptionPane.showMessageDialog(null, "Os campos não podem estar vazios!");
}
        else{
            
            venda.setCodFuncionario(Integer.parseInt(txtCodFuncionario.getText()));
            VendaDAO dao = new VendaDAO();
            dao.abrirVenda(venda);
            JOptionPane.showMessageDialog(null, "Venda aberta!");
            txtCodVenda.setText(String.valueOf(dao.retornaCodVenda()));
              
        }
    }//GEN-LAST:event_btnAbirVendaActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        VendaBeans venda = new VendaBeans();
        
        venda.setCodProduto(Integer.parseInt(txtCodProduto.getText()));
        venda.setCodPedido(Integer.parseInt(txtCodVenda.getText()));
        venda.setQtdItem(Integer.parseInt(txtQunatidade.getText()));
        
        if ((txtQunatidade.getText().isEmpty()) || ((txtCodVenda.getText().isEmpty() || (txtCodProduto.getText().isEmpty())))) {
   JOptionPane.showMessageDialog(null, "Os campos não podem estar vazios!");
   
}
        
        else{
            VendaDAO dao = new VendaDAO();
            
            ProdutoDAO pdao = new ProdutoDAO();
            int quantidade = pdao.bucarQuantidade(Integer.parseInt(txtCodProduto.getText()));
            
            if(quantidade >= Integer.parseInt(txtQunatidade.getText())){
                dao.inserirItem(venda);
                JOptionPane.showMessageDialog(null, "Item inserido com sucesso! ");
                
    
                valorTotal = dao.somaItem(Integer.parseInt(txtCodVenda.getText()));
                txtValorTotal.setText(String.valueOf(valorTotal));
                
                int novaQuantidade = quantidade - Integer.parseInt(txtQunatidade.getText());
                ProdutoBeans produto = new ProdutoBeans();
                produto.setQuantidade(novaQuantidade);
                produto.setCodProduto(Integer.parseInt(txtCodProduto.getText()));
                
                
                pdao.baixarEstoque(produto);
                
                listarItens();
                       

                txtQunatidade.setText("");
                txtValorItem.setText("");
                txtCodProduto.setText("");
                
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Quantidade insuficiente no estoque!");
                txtQunatidade.setText("");
                txtValorItem.setText("");
                txtCodProduto.setText("");
            }

        }
        
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Venda Finalizada!");
        txtCodVenda.setText("");
        txtValorTotal.setText("");
        
        modeloTabela modelo = (modeloTabela) tabelaItemVenda.getModel();
       
        int rowCount = modelo.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            modelo.remove(i);      
    }
        modelo = (modeloTabela) tabelaPesquisa.getModel();
        rowCount = modelo.getRowCount();
        
        for (int i = rowCount - 1; i >= 0; i--) {
            modelo.remove(i);      
    }
        
    }//GEN-LAST:event_btnFinalizarActionPerformed

     public void ListarProdutos(){
     
        ProdutoDAO dao = new ProdutoDAO();
        
        ArrayList dados = new ArrayList();
        dados = dao.preencherTabela(txtPesquisa.getText());
        
        String[] colunas = new String[]{"Codigo", "Descricao", "Marca", "Preço"};
       
        modeloTabela modelo = new modeloTabela(dados, colunas);
        
        tabelaPesquisa.setModel(modelo);
        tabelaPesquisa.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelaPesquisa.getColumnModel().getColumn(0).setResizable(false);
        
        tabelaPesquisa.getColumnModel().getColumn(1).setPreferredWidth(180);
        tabelaPesquisa.getColumnModel().getColumn(1).setResizable(false);
        
        tabelaPesquisa.getColumnModel().getColumn(2).setPreferredWidth(150);
        tabelaPesquisa.getColumnModel().getColumn(2).setResizable(false);
        
        tabelaPesquisa.getColumnModel().getColumn(3).setPreferredWidth(150);
        tabelaPesquisa.getColumnModel().getColumn(3).setResizable(false);
        
        tabelaPesquisa.setAutoResizeMode(tabelaPesquisa.AUTO_RESIZE_OFF);
        tabelaPesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
       
    }
     
     public void listarItens(){
     
        VendaDAO dao = new VendaDAO();
        
        ArrayList dados = new ArrayList();
        dados = dao.preencherTabelaItem(Integer.parseInt(txtCodVenda.getText()));
        
        String[] colunas = new String[]{"Codigo", "Nome", "Preco", "Quantidade"};
       
        modeloTabela modelo = new modeloTabela(dados, colunas);
        
        tabelaItemVenda.setModel(modelo);
        tabelaItemVenda.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelaItemVenda.getColumnModel().getColumn(0).setResizable(false);
        
        tabelaItemVenda.getColumnModel().getColumn(1).setPreferredWidth(180);
        tabelaItemVenda.getColumnModel().getColumn(1).setResizable(false);
        
        tabelaItemVenda.getColumnModel().getColumn(2).setPreferredWidth(150);
        tabelaItemVenda.getColumnModel().getColumn(2).setResizable(false);
        
        tabelaItemVenda.getColumnModel().getColumn(3).setPreferredWidth(150);
        tabelaItemVenda.getColumnModel().getColumn(3).setResizable(false);
       
        
        tabelaItemVenda.setAutoResizeMode(tabelaItemVenda.AUTO_RESIZE_OFF);
        tabelaItemVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
       
    }
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbirVenda;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaItemVenda;
    private javax.swing.JTable tabelaPesquisa;
    private javax.swing.JTextField txtCodFuncionario;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JTextField txtCodVenda;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtQunatidade;
    private javax.swing.JTextField txtValorItem;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
